version: "3.3"

services:
    api:
        build:
            context: ../
            dockerfile: ./docker/api.xplat.Dockerfile
        command: "sh -c '/app/QuestPDF.Server.Api'"
        ports:
            - "5877:5000"
        environment:
            - "Kestrel:Endpoints:Urls:Url=http://0.0.0.0:5000"
            - "QuestPDF:LicenseType=Community"
