version: "3.3"

services:
    api:
        build:
            context: ../
            dockerfile: ./docker/api.xplat.Dockerfile
        command: "sh -c '/app/QuestPDF.Server.Api'"
        ports:
            - "5877:5000"
        platform: linux/amd64
        environment:
            - "Kestrel__Endpoints__Urls__Url=http://0.0.0.0:5000"
            - "QuestPDF__LicenseType=Community"
