name: Build and Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-xplat-image:
        name: Build Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Api image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/api.xplat.Dockerfile
                  tags: ${{ secrets.DOCKER_TAGS }}
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}

    build-alpine-image:
        name: Build Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Api image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/api.Dockerfile
                  tags: ${{ secrets.DOCKER_ALPINE_TAGS }}
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
