name: Build and Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-image:
        name: Build Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Api image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./docker/api.xplat.Dockerfile
                  tags: ${{ secrets.DOCKER_TAGS }}
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
